version: '3'

services:
  database:
    container_name: demo1_db
    image: mysql/mysql-server:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: users_db
      MYSQL_ROOT_HOST: root
      MYSQL_ROOT_PASSWORD: Pp@2sword!
      TZ: 'Asia/Seoul'
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    networks:
      - test_network

  application:
    container_name: docker-compose-demo1
    restart: on-failure
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8098:8098"  # 애플리케이션 포트를 8098로 변경
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/users_db?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "Pp@2sword!"
    depends_on:
      - database
    networks:
      - test_network

networks:
  test_network:
